### ISSUE TITLE
mpv streaming from terminal (mpv) not working again despite upgrade

### ISSUE THREAD

**Issue by kaumidere** [chirag-droid/anime-cli#12]
hi there, it seems we have the same issue as last time with the the ability to stream from mpv not functioning as it should. every time i choose that option this is the output:

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yaundere/.local/lib/python3.10/site-packages/anime_cli/__main__.py", line 167, in <module>
    main()
  File "/home/yaundere/.local/lib/python3.10/site-packages/anime_cli/__main__.py", line 129, in main
    video_url = searchApi.get_video_url(embed_url)
  File "/home/yaundere/.local/lib/python3.10/site-packages/anime_cli/search/gogoanime.py", line 56, in get_video_url
    link = re.search(r"\s*sources.*", r.text).group()
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by markpaul099** [comment]
I'm also getting this exact error

**Comment by J-Reis** [comment]
Sadly, I lack the skill to actually help & can only pile on … but I'm seeing the same:
anime-cli 0.3.4 & mpv 0.34.1 in Termux on Android 10

Happy to provide any additional info
<details>
<summary>screenshot</summary>
![Screenshot_20220205-061957_Termux](https://user-images.githubusercontent.com/23666144/152642150-fcea542c-6047-433b-a640-478b2c99c95b.png)
</details>

**Comment by chirag-droid** [comment]
This project is going to be archived. use this now if you want to [chirag-droid/animeflix](https://github.com/chirag-droid/animeflix)
