### ISSUE TITLE
Broken when streaming to mpv?

### ISSUE THREAD

**Issue by ftorresc** [chirag-droid/anime-cli#4]
```
? What would you like to do for me? Stream on a video player (Recommended)
? Which video player would you like to use to stream? mpv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\wolf\anime-cli\anime_cli\__main__.py", line 129, in main
    video_url = searchApi.get_video_url(embed_url)
  File "C:\Users\wolf\anime-cli\anime_cli\search\gogoanime.py", line 55, in get_video_url
    link = re.search(r"\s*sources.*", r.text).group()
AttributeError: 'NoneType' object has no attribute 'group'
```

Streaming to browser works perfectly otherwise

**Comment by chirag-droid** [comment]
hey can you tell me what anime you were watching and what episode?

also make sure that mpv is installed, running this should this return the mpv version
```
mpv --version
```

Sorry, for a very late response I was bit busy

**Comment by ftorresc** [comment]
The problem was happening with all animes (despite the streaming to browser working perfectly). I also have mpv 0.33.0-397 installed. However, something seems to have broken, as I now can't get past the anime choice. 
```
Traceback (most recent call last):
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\wolf\AppData\Local\Programs\Python\Python39\Scripts\anime-cli.exe\__main__.py", line 7, in <module>
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\site-packages\anime_cli\__main__.py", line 109, in main
    anime = anime_prompt(searchApi)
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\site-packages\anime_cli\__main__.py", line 48, in anime_prompt
    return inquirer.select(
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\site-packages\InquirerPy\prompts\list.py", line 193, in __init__
    self.content_control = InquirerPyListControl(
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\site-packages\InquirerPy\prompts\list.py", line 60, in __init__
    super().__init__(
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\site-packages\InquirerPy\base\control.py", line 73, in __init__
    self._safety_check()
  File "c:\users\wolf\appdata\local\programs\python\python39\lib\site-packages\InquirerPy\base\control.py", line 156, in _safety_check
    raise InvalidArgument("argument choices cannot be empty")
InquirerPy.exceptions.InvalidArgument: argument choices cannot be empty
```

I'll be closing this as it surely broke on my machine. Thank you for your time.

**Comment by chirag-droid** [comment]
I know this exception occurs when it doesn't find any anime, I will fix it

**Comment by chirag-droid** [comment]
I have plans for a rewrite of the api and host it, so users don't have to download those additional libraries

**Comment by chirag-droid** [comment]
I have fixed the `argument choices cannot be empty` issue, although streaming to browser is still broken update anime-cli by running
```
pip install anime-cli --upgrade
```

**Comment by chirag-droid** [comment]
I have fixed this issue completely, just upgrade your anime-cli version. Thanks for reporting it

**Comment by ashhad** [comment]
Facing the same issue while using the tool on termux. OnePlus 8Pro Android 11.
Doesn't work on browser as well. When browser is selected it simply exits.

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/anime-cli", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/anime_cli/__main__.py", line 129, in main
    video_url = searchApi.get_video_url(embed_url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/anime_cli/search/gogoanime.py", line 56, in get_video_url
    link = re.search(r"\s*sources.*", r.text).group()
AttributeError: 'NoneType' object has no attribute 'group'
