### ISSUE TITLE
Opening the video in mpv player is not working.

### ISSUE THREAD

**Issue by Ahmedk-n** [chirag-droid/anime-cli#8]
I tried to play the anime on mpv and I got this :
`? What would you like to do for me? Stream on a video player (Recommended)
? Which video player would you like to use to stream? mpv
Starting proxy server on ('localhost', 8081)
It may take some time to open the video player. Be Patient :)
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\AHMED\AppData\Roaming\Python\Python39\site-packages\anime_cli\__main__.py", line 167, in <module>
    main()
  File "C:\Users\AHMED\AppData\Roaming\Python\Python39\site-packages\anime_cli\__main__.py", line 150, in main
    sp.Popen([video_player, video_url])
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by nbobic1** [comment]
u have to expose video player to $PATH
